using System;
using System.Collections.Generic;
using UnityEngine;
using GameDevTV.RTS.Units;
using GameDevTV.RTS.Player;
using GameDevTV.RTS.Utilities;

namespace GameDevTV.RTS.Environment
{
    public class SectorManager : MonoBehaviour
    {
        public static SectorManager Instance { get; private set; }

        public enum SectorFeature { None, Volcano, FaultLine, LavaTube, WaterDeposit }

        [System.Serializable]
        public class Sector
        {
            public Vector3 Center;
            public bool IsOccupied;
            public BaseBuilding OccupyingBuilding;
            public bool IsLocked = true;
            public bool IsExplored = false;
            public bool IsDiscovered = false;   // "???" state — partial visibility showing node markers
            public SectorFeature Feature = SectorFeature.None;
            public List<SectorNode> Nodes = new List<SectorNode>();  // Pre-placed nodes in this sector
            [System.NonSerialized] public List<BuildingSiteSlot> BuildingSites = new List<BuildingSiteSlot>(); // Runtime-only; generated by PlanetGenerator
            [System.NonSerialized] public List<BuildingSiteCluster> BuildingClusters = new List<BuildingSiteCluster>();

            /// <summary>Terraforming progress (0–1) recorded when this sector's generation round completes.</summary>
            [System.NonSerialized] public float TerraformingCompletionPercent;
            /// <summary>Generation index whose goals were satisfied in this sector (0 if none yet).</summary>
            [System.NonSerialized] public int CompletedGenerationRound;
        }

        public List<Sector> Sectors = new List<Sector>();
        public Sector ActiveSector { get; set; }

        /// <summary>
        /// Sector climate ticks apply to this round. Mid-round unlocks must not overwrite it
        /// or atmosphere buildings in the player's colony go silent.
        /// </summary>
        public Sector TerraformingSector { get; private set; }

        /// <summary>
        /// Pin climate focus for the current generation. Use on gen start / post-round handoff.
        /// </summary>
        public void BeginTerraformingOn(Sector sector)
        {
            if (sector == null) return;
            TerraformingSector = sector;
            ActiveSector = sector;
            Debug.Log($"[SectorManager] Terraforming focus set to sector at {sector.Center}.");
        }

        /// <summary>Stable climate focus — prefers <see cref="TerraformingSector"/> over last unlock.</summary>
        public Sector GetClimateFocusSector()
        {
            if (TerraformingSector != null && !TerraformingSector.IsLocked)
                return TerraformingSector;
            return ActiveSector;
        }

        /// <summary>
        /// True when this building belongs to the active sector's mini-game
        /// (on a terraforming-sector pad, or nearer to that sector than any other).
        /// </summary>
        public bool IsBuildingInActiveSector(BaseBuilding building)
        {
            if (building == null) return false;
            Sector focus = GetClimateFocusSector();
            if (focus == null) return true;

            if (Sectors != null)
            {
                foreach (var sector in Sectors)
                {
                    if (sector?.BuildingSites == null) continue;
                    foreach (var site in sector.BuildingSites)
                    {
                        if (site == null || site.OccupyingBuilding != building) continue;
                        return sector == focus;
                    }
                }
            }

            if (focus.OccupyingBuilding == building)
                return true;

            Sector nearest = GetNearestSector(building.transform.position);
            return nearest == focus;
        }

        /// <summary>
        /// Climate contribution check that prefers reserved-pad ownership and falls back to
        /// geographic sector bounds. Edge pads must not be silenced by nearest-center alone.
        /// </summary>
        public bool DoesBuildingCountForActiveClimate(BaseBuilding building)
        {
            if (building == null) return false;
            Sector focus = GetClimateFocusSector();
            if (focus == null) return true;

            if (BuildingSiteRegistry.TryGetSiteForBuilding(building, out BuildingSiteSlot site)
                && site.Sector != null)
            {
                return site.Sector == focus;
            }

            return IsBuildingInActiveSector(building);
        }

        private float secW;
        private float secH;
        private List<GameObject> borderInstances = new List<GameObject>();

        /// <summary>Fired whenever a previously locked sector becomes unlocked.</summary>
        public static event Action OnSectorUnlocked;

        /// <summary>Fired when a sector is explored (scouted) but not necessarily unlocked yet.</summary>
        public static event Action<int> OnSectorExplored;

        private void Awake()
        {
            Instance = this;
        }

        private void OnDestroy()
        {
            if (Instance == this)
                Instance = null;
        }

        private void OnEnable()
        {
            PlanetGenerator.OnPlanetGenerated += InitializeSectors;
        }

        private void OnDisable()
        {
            PlanetGenerator.OnPlanetGenerated -= InitializeSectors;
        }

        private void Start()
        {
            InitializeSectors();
        }

        private bool _hasInitialized = false;

        public void InitializeSectors()
        {
            if (_hasInitialized) return;

            var pg = PlanetGenerator.Instance;
            if (pg == null) pg = UnityEngine.Object.FindAnyObjectByType<PlanetGenerator>();
            
            if (pg == null || pg.Config == null) 
            {
                Debug.LogWarning("[SectorManager] Cannot initialize sectors: PlanetGenerator or Config is null.");
                return;
            }

            _hasInitialized = true;

            var config = pg.Config;
            float cellSize = pg.CellSize;
            float worldWidth = config.MapWidth * cellSize;
            float worldHeight = config.MapHeight * cellSize;

            Sectors.Clear();

            secW = worldWidth / config.SectorsX;
            secH = worldHeight / config.SectorsY;

            int startingX = config.SectorsX / 2;
            int startingY = config.SectorsY / 2;
            var sectorCoordinates = new List<Vector2Int> { new Vector2Int(startingX, startingY) };

            for (int y = 0; y < config.SectorsY; y++)
            {
                for (int x = 0; x < config.SectorsX; x++)
                {
                    if (x == startingX && y == startingY) continue;
                    sectorCoordinates.Add(new Vector2Int(x, y));
                }
            }

            for (int i = 0; i < sectorCoordinates.Count; i++)
            {
                    int x = sectorCoordinates[i].x;
                    int y = sectorCoordinates[i].y;
                    Vector3 center = new Vector3(
                        (x + 0.5f) * secW,
                        0,
                        (y + 0.5f) * secH
                    );

                    // Snap to ground height
                    if (Physics.Raycast(center + Vector3.up * 100f, Vector3.down, out RaycastHit hit, 200f, LayerMask.GetMask("Default", "Terrain")))
                    {
                        center.y = hit.point.y;
                    }

                    bool isFirst = i == 0;
                    SectorFeature feature = SectorFeature.None;
                    if (!isFirst)
                    {
                        int featureIndex = 1 + ((Sectors.Count - 1) % 4);
                        feature = (SectorFeature)featureIndex;
                    }
                    Sectors.Add(new Sector { Center = center, IsOccupied = false, IsLocked = !isFirst, IsExplored = isFirst, Feature = feature });
            }
            
            if (Sectors.Count > 0)
            {
                BeginTerraformingOn(Sectors[0]);

                // Force-discover Minerals and Gas in Sector 0 so the player can bootstrap.
                // All other sectors require discovery cards to reveal resource types.
                DiscoverySystem.RevealResourceType("Minerals");
                DiscoverySystem.RevealResourceType("Gas");

                DiscoverResourcesInUnlockedSectors();
                UpdateSectorBorders();
                OnSectorUnlocked?.Invoke();
            }
            Debug.Log($"[SectorManager] Initialized {Sectors.Count} sectors for {worldWidth}x{worldHeight} map. Sector 0 is unlocked.");
        }

        public void ReinitializeSectors()
        {
            _hasInitialized = false;
            Sectors.Clear();
            borderInstances.Clear();
            InitializeSectors();
        }

        public void DiscoverResourcesInUnlockedSectors()
        {
            var hiddenResources = UnityEngine.Object.FindObjectsByType<HiddenResource>(FindObjectsInactive.Include);
            foreach (var hr in hiddenResources)
            {
                if (hr == null || hr.IsDiscovered) continue;

                var nearestSector = GetNearestSector(hr.transform.position);
                if (nearestSector != null && !nearestSector.IsLocked)
                {
                    hr.Discover();
                }
            }
        }

        private bool hasDoneStartingDiscovery = false;

        private void Update()
        {
            if (Sectors.Count == 0 && Time.timeSinceLevelLoad > 1f)
            {
                InitializeSectors();
            }
            UpdateOccupancy();

            if (!hasDoneStartingDiscovery && Sectors.Count > 0 && Time.timeSinceLevelLoad > 0.1f)
            {
                hasDoneStartingDiscovery = true;
                DiscoverResourcesInUnlockedSectors();
                Debug.Log("[SectorManager] Completed deferred starting resource discovery for unlocked sectors!");
            }
        }

        private void UpdateOccupancy()
        {
            foreach (var sector in Sectors)
            {
                bool found = false;

                // Check if the starting base (GlobalCommander) occupies this sector
                var commander = FindAnyObjectByType<GlobalCommander>();
                if (commander != null && GetNearestSector(commander.transform.position) == sector)
                {
                    found = true;
                    if (ActiveSector == null) ActiveSector = sector;
                }

                if (!found)
                {
                    foreach (var building in BaseBuilding.ActiveBuildings)
                    {
                        if (building.Owner != GameOverManager.MonitoredOwner) continue;
                        if (building.Progress.State != BuildingProgress.BuildingState.Completed) continue;
                        
                        // Check if it's a Command Post (using name contains check like in CompleteConstruction)
                        bool isCommandPost = building.BuildingSO != null && building.BuildingSO.Name.Contains("Command", System.StringComparison.OrdinalIgnoreCase);
                        if (!isCommandPost) continue;

                        if (GetNearestSector(building.transform.position) == sector)
                        {
                            found = true;
                            sector.OccupyingBuilding = building;
                            if (ActiveSector == null) ActiveSector = sector;
                            break;
                        }
                    }
                }

                sector.IsOccupied = found;
                if (!found) sector.OccupyingBuilding = null;
            }
        }

        public Sector GetNearestSector(Vector3 position)
        {
            if (Sectors == null || Sectors.Count == 0) return null;

            Sector nearest = null;
            float minDistance = float.MaxValue;

            foreach (var sector in Sectors)
            {
                float dist = Vector3.Distance(position, sector.Center);
                if (dist < minDistance)
                {
                    minDistance = dist;
                    nearest = sector;
                }
            }

            return nearest;
        }

        public bool AreAllSectorsOccupied()
        {
            if (Sectors.Count == 0) 
            {
                InitializeSectors();
                if (Sectors.Count == 0) return false;
            }

            foreach (var s in Sectors)
            {
                if (!s.IsOccupied) return false;
            }
            return true;
        }

        public void UnlockNextSector()
        {
            for (int i = 0; i < Sectors.Count; i++)
            {
                if (Sectors[i].IsLocked)
                {
                    // Only unlock if the sector has been explored first
                    if (!Sectors[i].IsExplored)
                    {
                        Debug.LogWarning($"[SectorManager] Cannot unlock Sector {i} — it has not been explored yet. Use scouting cards to explore it first.");
                        return;
                    }

                    Sectors[i].IsLocked = false;
                    // Unlock must not steal TerraformingSector / climate focus mid-round.
                    if (ActiveSector == null) ActiveSector = Sectors[i];
                    Debug.Log($"[SectorManager] Sector {i} unlocked (climate focus stays on terraforming sector).");
                    // Do not mass-reveal deposits here — ExplorationManager.RevealGatherableAtNode
                    // (and discovery cards) are what uncover materials node-by-node.
                    SectorColonization.PrepareNewlyUnlockedSector(Sectors[i], Owner.Player1, i);
                    UpdateSectorBorders();
                    OnSectorUnlocked?.Invoke();
                    return; // Only unlock one at a time
                }
            }
            Debug.Log("[SectorManager] All sectors are already unlocked!");
        }

        /// <summary>Index of the locked sector whose center is closest to <paramref name="fromPosition"/>.</summary>
        public int GetClosestLockedSectorIndex(Vector3 fromPosition)
        {
            if (Sectors == null || Sectors.Count == 0) return -1;

            int closest = -1;
            float minDistSq = float.MaxValue;
            for (int i = 0; i < Sectors.Count; i++)
            {
                var sector = Sectors[i];
                if (sector == null || !sector.IsLocked) continue;
                float distSq = (sector.Center - fromPosition).sqrMagnitude;
                if (distSq < minDistSq)
                {
                    minDistSq = distSq;
                    closest = i;
                }
            }

            return closest;
        }

        public int GetClosestLockedSectorIndex(Sector fromSector)
        {
            if (fromSector == null) return GetClosestLockedSectorIndex(Vector3.zero);
            return GetClosestLockedSectorIndex(fromSector.Center);
        }

        /// <summary>
        /// Index of the nearest sector that still needs a Command Post claim
        /// (locked, or unlocked with an empty CP pad).
        /// </summary>
        public int GetClosestSectorNeedingCommandPostIndex(Vector3 fromPosition)
        {
            if (Sectors == null || Sectors.Count == 0) return -1;

            int closest = -1;
            float minDistSq = float.MaxValue;
            for (int i = 0; i < Sectors.Count; i++)
            {
                var sector = Sectors[i];
                if (sector == null || !SectorNeedsCommandPost(sector)) continue;

                float distSq = (sector.Center - fromPosition).sqrMagnitude;
                if (distSq < minDistSq)
                {
                    minDistSq = distSq;
                    closest = i;
                }
            }

            return closest;
        }

        public static bool SectorNeedsCommandPost(Sector sector)
        {
            if (sector == null || sector.IsOccupied) return false;
            if (sector.BuildingSites == null || sector.BuildingSites.Count == 0) return sector.IsLocked;

            foreach (var site in sector.BuildingSites)
            {
                if (site != null && site.Kind == BuildingSiteKind.CommandPost && !site.IsOccupied)
                    return true;
            }

            return false;
        }

        /// <summary>
        /// Unlock a sector for building and auto-place its Command Post (no exploration card required).
        /// </summary>
        /// <param name="claimTerraformingFocus">
        /// True when advancing after a finished sector round. False for mid-round scouting unlocks
        /// so existing pink climate buildings keep counting.
        /// </param>
        public bool UnlockAndColonizeSector(int index, Owner owner = Owner.Player1, bool claimTerraformingFocus = false)
        {
            if (index < 0 || index >= Sectors.Count) return false;
            var sector = Sectors[index];
            if (sector == null || !sector.IsLocked) return false;

            sector.IsLocked = false;
            sector.IsExplored = true;
            sector.IsDiscovered = true;
            if (claimTerraformingFocus || TerraformingSector == null)
                BeginTerraformingOn(sector);
            else if (ActiveSector == null)
                ActiveSector = sector;
            OnSectorExplored?.Invoke(index);
            SectorColonization.PrepareNewlyUnlockedSector(sector, owner, index);
            UpdateSectorBorders();
            OnSectorUnlocked?.Invoke();
            Debug.Log($"[SectorManager] Sector {index} auto-unlocked and colonized (claimFocus={claimTerraformingFocus}).");
            return true;
        }

        /// <summary>Mark a sector as discovered (partial visibility — shows "???" markers).</summary>
        public void DiscoverSector(int index)
        {
            if (index < 0 || index >= Sectors.Count) return;
            if (Sectors[index].IsDiscovered) return;
            if (!Sectors[index].IsLocked) return;  // Already unlocked, no need for discovery state

            Sectors[index].IsDiscovered = true;
            Debug.Log($"[SectorManager] Sector {index} discovered — showing markers!");
        }

        /// <summary>
        /// Mark a specific sector as having its first node explored.
        /// This is called by ExplorationManager when a node in a locked sector is explored.
        /// </summary>
        public void OnFirstNodeExploredInSector(int index, Owner owner = Owner.Player1)
        {
            if (index < 0 || index >= Sectors.Count) return;
            if (!Sectors[index].IsLocked) return;

            UnlockAndColonizeSector(index, owner);
            Debug.Log($"[SectorManager] Sector {index} unlocked via node exploration!");
        }

        /// <summary>Mark a specific sector as explored.</summary>
        public void ExploreSector(int index)
        {
            if (index < 0 || index >= Sectors.Count) return;
            if (Sectors[index].IsExplored) return;
            Sectors[index].IsExplored = true;
            OnSectorExplored?.Invoke(index);
        }

        /// <summary>
        /// Check if a sector has a specific feature (e.g., LavaTube) that has been revealed.
        /// </summary>
        public bool SectorHasFeature(int sectorIndex, SectorFeature feature)
        {
            if (sectorIndex < 0 || sectorIndex >= Sectors.Count) return false;
            var sector = Sectors[sectorIndex];
            if (!sector.IsExplored) return false;
            return sector.Feature == feature;
        }

        /// <summary>Explore the next locked sector. Returns the index, or -1 if none remain.</summary>
        public int ExploreNextSector()
        {
            for (int i = 0; i < Sectors.Count; i++)
            {
                if (Sectors[i].IsLocked && !Sectors[i].IsExplored)
                {
                    Sectors[i].IsExplored = true;
                    OnSectorExplored?.Invoke(i);
                    Debug.Log($"[SectorManager] Sector {i} explored (scouted).");
                    return i;
                }
            }
            return -1;
        }

        /// <summary>Get the index of the next locked sector, or -1 if none remain.</summary>
        public int GetNextLockedSectorIndex()
        {
            for (int i = 0; i < Sectors.Count; i++)
            {
                if (Sectors[i].IsLocked) return i;
            }
            return -1;
        }

        /// <summary>Count map sectors the player has unlocked for building.</summary>
        public int GetUnlockedSectorCount()
        {
            int count = 0;
            foreach (var sector in Sectors)
            {
                if (sector != null && !sector.IsLocked) count++;
            }
            return count;
        }

        /// <summary>Get the index of the next locked AND unexplored sector, or -1 if none.</summary>
        public int GetNextUnexploredSectorIndex()
        {
            for (int i = 0; i < Sectors.Count; i++)
            {
                if (Sectors[i].IsLocked && !Sectors[i].IsExplored) return i;
            }
            return -1;
        }

        public void UpdateSectorBorders()
        {
            // Clean up old borders
            foreach (var go in borderInstances)
            {
                if (go != null) Destroy(go);
            }
            borderInstances.Clear();

            if (secW <= 0f || secH <= 0f) return;

            // Create borders for unlocked sectors
            for (int i = 0; i < Sectors.Count; i++)
            {
                var sector = Sectors[i];
                if (sector == null || sector.IsLocked) continue;

                GameObject borderGo = new GameObject("SectorBorder_" + i);
                borderGo.transform.SetParent(transform);
                borderInstances.Add(borderGo);

                LineRenderer line = borderGo.AddComponent<LineRenderer>();
                line.positionCount = 5;
                line.startWidth = 0.6f;
                line.endWidth = 0.6f;
                
                // Cyan sci-fi holographic style color
                Color cyanColor = new Color(0f, 0.9f, 0.9f, 0.8f);
                line.startColor = cyanColor;
                line.endColor = cyanColor;

                // Simple additive/sprite shader
                Shader defaultShader = Shader.Find("Sprites/Default");
                if (defaultShader != null)
                {
                    line.material = new Material(defaultShader);
                }

                line.useWorldSpace = true;
                line.loop = true;

                // Compute corner coordinates
                float minX = sector.Center.x - secW / 2f;
                float maxX = sector.Center.x + secW / 2f;
                float minZ = sector.Center.z - secH / 2f;
                float maxZ = sector.Center.z + secH / 2f;

                Vector3[] corners = new Vector3[5];
                corners[0] = new Vector3(minX, 0f, minZ);
                corners[1] = new Vector3(maxX, 0f, minZ);
                corners[2] = new Vector3(maxX, 0f, maxZ);
                corners[3] = new Vector3(minX, 0f, maxZ);
                corners[4] = new Vector3(minX, 0f, minZ);

                // Sample heights to stick the lines to the terrain
                for (int j = 0; j < 5; j++)
                {
                    float y = 0.5f; // fallback slightly above zero
                    if (Physics.Raycast(new Vector3(corners[j].x, 100f, corners[j].z), Vector3.down, out RaycastHit hit, 200f, LayerMask.GetMask("Default", "Terrain")))
                    {
                        y = hit.point.y + 0.2f; // float slightly above ground to prevent z-fighting
                    }
                    corners[j].y = y;
                }

                line.SetPositions(corners);
            }
        }

        private void OnDrawGizmos()
        {
            if (Sectors == null) return;
            foreach (var sector in Sectors)
            {
                Gizmos.color = sector.IsOccupied ? Color.green : Color.red;
                Gizmos.DrawWireSphere(sector.Center, 2f);
                
                if (PlanetGenerator.Instance != null && PlanetGenerator.Instance.Config != null)
                {
                    Gizmos.color = new Color(Gizmos.color.r, Gizmos.color.g, Gizmos.color.b, 0.2f);
                    Gizmos.DrawWireSphere(sector.Center, PlanetGenerator.Instance.Config.SectorOccupationRadius);
                }
            }
        }
    }
}
